### ISSUE TITLE
trian problem

### ISSUE THREAD

**Issue by gongliuqing123** [TianmingQiu/Hydraplus_Net#1]
在训练中、先训练MNet、然后将AF1、AF2以及AF3全部训练一遍、还是只是训练其中一个就行。
训练完之后是用att_vis预测结果吗？

**Comment by TianmingQiu** [comment]
对，根据论文的话，先训练MNet、然后将AF1、AF2以及AF3全部训练一遍。然后还要接着训练Hydraplus的最后几层。然后再跑test.py。就可以得到attention的[pickle](https://github.com/TianmingQiu/HydraPlusNet/blob/master/test.py#L124). 然后再用att_vis看可视化结果。我这个代码还在更新修改中，att_vis仅供参考。
